# Generated by Django 4.0.6 on 2022-07-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
