# Generated by Django 4.0.6 on 2022-07-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_assignment_courses_employee_results_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='Assignment_ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='Student_Roll_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='Teacher_ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Course_ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Course_Price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Employee_ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Employee_Salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Teacher_ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='results',
            name='Marks_Obtained',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='results',
            name='Result_ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='results',
            name='Students_ID',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='Student_Phoneno',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='students',
            name='Student_Roll_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Course_ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Teacher_Phone',
            field=models.IntegerField(default=0),
        ),
    ]
